//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_Macro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorIncidents
    {
        public MajorIncidents()
        {
            this.Timeline = new HashSet<Timeline>();
        }
    
        public int incidentNumber { get; set; }
        public string descr { get; set; }
        public string product { get; set; }
        public string dataCenter { get; set; }
        public int categorization { get; set; }
        public int customerType { get; set; }
        public string topCustomers { get; set; }
    
        public virtual ICollection<Timeline> Timeline { get; set; }
    }
}
