//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOC_Macro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline
    {
        public int id { get; set; }
        public int incidentNumber { get; set; }
        public System.DateTime time { get; set; }
        public string description { get; set; }
    
        public virtual MajorIncidents MajorIncidents { get; set; }
    }
}
